#!/bin/python
if __name__ == '__main__':
    a = int(raw_input())    #for taking input from user
    b = int(raw_input())    #for taking input from user
    print(a+b)              #it will print the sum
    print(a-b)              #it will print the difference
    print(a*b)              #it will print the product
