#!/bin/python
from __future__ import print_function

if __name__ == '__main__':
    n = int(raw_input())      #taking input from user
    for i in range(1,n+1):
        print(i,end='')       #end="" is used for printing the output in the same line

